In [1]:
# import required libraries
import pandas as pd
import numpy as np
import statistics as st
import matplotlib.pyplot as plt
import statsmodels.api as sm

# read the HeroesPymoli data
covid_tiny = pd.read_csv("/Users/rodneydavermann/Desktop/project/merged_data.csv")
covid_tiny.head()

,Unnamed: 0,date,state,cases,deaths,mental disorder,frequency of mental disorder
0,0,4/23/2020,Alabama,5832,197,Symptoms of Depressive Disorder,18.6
1,1,4/23/2020,Alabama,5832,197,Symptoms of Anxiety Disorder,25.6
2,2,4/23/2020,Alabama,5832,197,Symptoms of Anxiety Disorder or Depressive Dis...,30.3
3,3,4/23/2020,Alaska,335,7,Symptoms of Depressive Disorder,19.2
4,4,4/23/2020,Alaska,335,7,Symptoms of Anxiety Disorder,27.7

In [2]:
# Frequency table by state
covid_tiny_group = covid_tiny.groupby("state")
covid_tiny_group

# total number of cases, deaths, and frequency of mental disorder by state
total_cases_state = covid_tiny_group["cases"].mean().map("{:,.0f}".format)
total_deaths_state = covid_tiny_group["deaths"].mean().map("{:,.0f}".format)
total_frequency_mental_disorder_state = covid_tiny_group["frequency of mental disorder"].mean().map("{:,.1f}".format)
total_cases_state
total_deaths_state
total_frequency_mental_disorder_state

# Display the results in a dataframe 
covid_tiny_group_results = pd.DataFrame({"Average Cases": total_cases_state  ,"Average Deaths": total_deaths_state,
                                        "Average Frequency of Mental Disorder": total_frequency_mental_disorder_state})

# sort the dataframe from the total cases column
covid_tiny_group_results = covid_tiny_group_results.sort_values(["Average Cases"], ascending=False)
covid_tiny_group_results

,Average Cases,Average Deaths,Average Frequency of Mental Disorder
state,,,
Kansas,"96,606","1,336",30.3
Texas,"890,327","15,310",34.2
Nebraska,"72,557",766,27.5
Florida,"696,439","12,443",33.5
New York,"662,902","33,856",31.9
New Mexico,"59,253","1,268",35.2
Idaho,"58,779",629,29.9
Oregon,"49,915",749,35.3
Illinois,"443,957","10,607",32.4
Rhode Island,"43,900","1,218",31.3
Vermont,"4,174",86,30.0
South Dakota,"39,898",570,26.2
West Virginia,"36,159",645,34.5
North Dakota,"35,885",506,25.8
Georgia,"339,544","6,654",33.0
New Jersey,"311,223","15,704",32.0
Montana,"31,031",397,28.7
Pennsylvania,"300,115","10,255",31.3
Delaware,"30,036",665,29.1
Ohio,"295,006","5,775",32.0
North Carolina,"275,707","3,956",30.7
Arizona,"270,855","5,512",33.5
Tennessee,"253,642","3,405",32.6
Michigan,"234,014","8,485",31.2
Indiana,"218,272","4,826",32.2
Massachusetts,"213,707","9,577",30.4
Wisconsin,"212,938","2,400",27.6
New Hampshire,"21,020",511,29.3
Virginia,"191,987","3,367",30.4
Missouri,"179,900","2,966",31.7
Alabama,"173,987","3,082",32.5
Louisiana,"171,878","5,147",37.0
Alaska,"17,894",86,31.6
District of Columbia,"17,822",623,32.2
Minnesota,"168,348","2,726",27.1
South Carolina,"166,328","3,112",30.7
Wyoming,"16,712",178,29.1
Maryland,"151,067","4,112",30.2
Colorado,"141,365","2,698",32.4
Oklahoma,"129,588","1,400",34.4
Iowa,"123,860","1,909",28.3
Kentucky,"122,409","1,631",33.9
Washington,"120,977","2,326",32.9
Utah,"120,013",637,30.9
Maine,"12,305",226,30.2
Mississippi,"107,452","2,768",36.1
Arkansas,"106,179","1,719",34.3
Nevada,"101,130","1,742",36.2
Connecticut,"100,530","4,810",31.1
Hawaii,"10,543",149,29.5
California,"1,112,002","17,291",34.8

In [3]:
# Frequency table by mental disorder
covid_tiny_group1 = covid_tiny.groupby("mental disorder")
covid_tiny_group1

# total number of cases, deaths, and frequency of mental disorder by mental disorder
total_cases_mental_disorder = covid_tiny_group1["cases"].mean().map("{:,.0f}".format)
total_deaths_mental_disorder = covid_tiny_group1["deaths"].mean().map("{:,.0f}".format)
total_frequency_mental_disorder = covid_tiny_group1["frequency of mental disorder"].mean().map("{:,.1f}".format)
total_cases_mental_disorder
total_deaths_mental_disorder
total_frequency_mental_disorder

# Display the results in a dataframe 
covid_tiny_group_mental_disorder_results = pd.DataFrame({"Average of Cases": total_cases_mental_disorder,"Average of Deaths":total_deaths_mental_disorder,
                                        "Average Frequency of Mental Disorder": total_frequency_mental_disorder})
covid_tiny_group_mental_disorder_results

,Average of Cases,Average of Deaths,Average Frequency of Mental Disorder
mental disorder,,,
Symptoms of Anxiety Disorder,"191,414","4,369",32.1
Symptoms of Anxiety Disorder or Depressive Disorder,"191,414","4,369",37.0
Symptoms of Depressive Disorder,"191,414","4,369",25.6

In [4]:
# create a new lists with cases, deaths, and frequency of mental disorder columns
cases_column = covid_tiny["cases"].to_list()
deaths_column = covid_tiny["deaths"].to_list()
frequency_column = covid_tiny["frequency of mental disorder"].to_list()

# tuple from the above lists
new_covid_tiny = list(zip(cases_column,deaths_column,frequency_column))

# create a new dataframe to describe the numerical variables
new_covid_tiny_df = pd.DataFrame(new_covid_tiny, columns=["cases", "deaths", "Frequency of Mental Disorder"])
round(new_covid_tiny_df.describe(),2)

            cases    deaths  Frequency of Mental Disorder
count     4131.00   4131.00                       4131.00
mean    191414.42   4368.86                         31.56
std     365537.50   7356.73                          6.45
min        335.00      7.00                         14.30
25%      15053.00    414.00                         26.80
50%      60820.00   1512.00                         31.50
75%     202182.00   5004.00                         36.20
max    3631735.00  56952.00                         52.30

In [8]:
# simple linear regression with the OLS: cases vs frequency of mental disorder

#define the independent, and the dependent variables 
x=covid_tiny[["cases"]]
y=covid_tiny[["frequency of mental disorder"]]

# define the model 
model_covid = sm.OLS(y,x).fit()
print(model_covid.summary())

                                      OLS Regression Results
=================================================================================================
Dep. Variable:     frequency of mental disorder   R-squared (uncentered):                   0.229
Model:                                      OLS   Adj. R-squared (uncentered):              0.229
Method:                           Least Squares   F-statistic:                              1229.
Date:                          Fri, 30 Apr 2021   Prob (F-statistic):                   7.46e-236
Time:                                  01:11:06   Log-Likelihood:                         -19669.
No. Observations:                          4131   AIC:                                  3.934e+04
Df Residuals:                              4130   BIC:                                  3.935e+04
Df Model:                                     1
Covariance Type:                      nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
cases       3.739e-05   1.07e-06     35.050      0.000    3.53e-05    3.95e-05
==============================================================================
Omnibus:                     3381.118   Durbin-Watson:                   0.210
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           102936.706
Skew:                          -3.752   Prob(JB):                         0.00
Kurtosis:                      26.275   Cond. No.                         1.00
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [6]:
# simple linear regression with the OLS: deaths vs frequency of mental disorder

#define the independent, and the dependent variables 
x=covid_tiny[["deaths"]]
y=covid_tiny[["frequency of mental disorder"]]

# define the model 
model_covid = sm.OLS(y,x).fit()
print(model_covid.summary())

                                      OLS Regression Results
=================================================================================================
Dep. Variable:     frequency of mental disorder   R-squared (uncentered):                   0.270
Model:                                      OLS   Adj. R-squared (uncentered):              0.270
Method:                           Least Squares   F-statistic:                              1528.
Date:                          Fri, 30 Apr 2021   Prob (F-statistic):                   1.07e-284
Time:                                  01:10:21   Log-Likelihood:                         -19556.
No. Observations:                          4131   AIC:                                  3.911e+04
Df Residuals:                              4130   BIC:                                  3.912e+04
Df Model:                                     1
Covariance Type:                      nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
deaths         0.0020   5.01e-05     39.093      0.000       0.002       0.002
==============================================================================
Omnibus:                     2333.264   Durbin-Watson:                   0.270
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            20666.770
Skew:                          -2.591   Prob(JB):                         0.00
Kurtosis:                      12.655   Cond. No.                         1.00
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [9]:
# multiple linear regression with the OLS: cases, deaths vs frequency of mental disorder

#define the independent, and the dependent variables 
x=covid_tiny[["cases","deaths"]]
y=covid_tiny[["frequency of mental disorder"]]

# define the model 
model_covid = sm.OLS(y,x).fit()
print(model_covid.summary())

                                      OLS Regression Results
=================================================================================================
Dep. Variable:     frequency of mental disorder   R-squared (uncentered):                   0.272
Model:                                      OLS   Adj. R-squared (uncentered):              0.271
Method:                           Least Squares   F-statistic:                              770.3
Date:                          Fri, 30 Apr 2021   Prob (F-statistic):                   5.21e-285
Time:                                  01:11:27   Log-Likelihood:                         -19551.
No. Observations:                          4131   AIC:                                  3.911e+04
Df Residuals:                              4129   BIC:                                  3.912e+04
Df Model:                                     2
Covariance Type:                      nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
cases       6.771e-06   2.23e-06      3.037      0.002     2.4e-06    1.11e-05
deaths         0.0017      0.000     15.514      0.000       0.001       0.002
==============================================================================
Omnibus:                     2450.812   Durbin-Watson:                   0.266
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            25508.485
Skew:                          -2.697   Prob(JB):                         0.00
Kurtosis:                      13.913   Cond. No.                         104.
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.