In [1]:
import pandas as pd
# File to Load
file_to_load = "Resources/anxiety_data.csv"

# Read CSV File and store into Pandas data frame
anx_data = pd.read_csv(file_to_load)
anx_data

,Indicator,Group,State,Subgroup,Phase,Time Period,Time Period Label,Time Period Start Date,Time Period End Date,Value,Low CI,High CI,Confidence Interval,Quartile Range
0,Symptoms of Depressive Disorder,National Estimate,United States,United States,1,1,Apr 23 - May 5,4/23/2020 0:00,5/5/2020 0:00,23.5,22.7,24.3,22.7 - 24.3,NaN
1,Symptoms of Depressive Disorder,By Age,United States,18 - 29 years,1,1,Apr 23 - May 5,4/23/2020 0:00,5/5/2020 0:00,32.7,30.2,35.2,30.2 - 35.2,NaN
2,Symptoms of Depressive Disorder,By Age,United States,30 - 39 years,1,1,Apr 23 - May 5,4/23/2020 0:00,5/5/2020 0:00,25.7,24.1,27.3,24.1 - 27.3,NaN
3,Symptoms of Depressive Disorder,By Age,United States,40 - 49 years,1,1,Apr 23 - May 5,4/23/2020 0:00,5/5/2020 0:00,24.8,23.3,26.2,23.3 - 26.2,NaN
4,Symptoms of Depressive Disorder,By Age,United States,50 - 59 years,1,1,Apr 23 - May 5,4/23/2020 0:00,5/5/2020 0:00,23.2,21.5,25.0,21.5 - 25.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5779,Symptoms of Anxiety Disorder or Depressive Dis...,By State,Virginia,Virginia,3 (Jan 6 ? Mar 29),27,Mar 17 - Mar 29,3/17/2021 0:00,3/29/2021 0:00,31.4,27.2,35.9,27.2 - 35.9,24.9-32.0
5780,Symptoms of Anxiety Disorder or Depressive Dis...,By State,Washington,Washington,3 (Jan 6 ? Mar 29),27,Mar 17 - Mar 29,3/17/2021 0:00,3/29/2021 0:00,35.6,32.9,38.5,32.9 - 38.5,34.8-36.2
5781,Symptoms of Anxiety Disorder or Depressive Dis...,By State,West Virginia,West Virginia,3 (Jan 6 ? Mar 29),27,Mar 17 - Mar 29,3/17/2021 0:00,3/29/2021 0:00,41.0,35.1,47.0,35.1 - 47.0,36.3-42.6
5782,Symptoms of Anxiety Disorder or Depressive Dis...,By State,Wisconsin,Wisconsin,3 (Jan 6 ? Mar 29),27,Mar 17 - Mar 29,3/17/2021 0:00,3/29/2021 0:00,32.3,28.3,36.4,28.3 - 36.4,32.1-34.7
5783,Symptoms of Anxiety Disorder or Depressive Dis...,By State,Wyoming,Wyoming,3 (Jan 6 ? Mar 29),27,Mar 17 - Mar 29,3/17/2021 0:00,3/29/2021 0:00,35.6,28.8,43.0,28.8 - 43.0,34.8-36.2

In [2]:
del anx_data['Group']
del anx_data['Subgroup']
del anx_data['Phase']
del anx_data['Time Period']
del anx_data['Time Period Label']
del anx_data['Time Period End Date']
del anx_data['Low CI']
del anx_data['High CI']
del anx_data['Confidence Interval']
del anx_data['Quartile Range']
anx_data

,Indicator,State,Time Period Start Date,Value
0,Symptoms of Depressive Disorder,United States,4/23/2020 0:00,23.5
1,Symptoms of Depressive Disorder,United States,4/23/2020 0:00,32.7
2,Symptoms of Depressive Disorder,United States,4/23/2020 0:00,25.7
3,Symptoms of Depressive Disorder,United States,4/23/2020 0:00,24.8
4,Symptoms of Depressive Disorder,United States,4/23/2020 0:00,23.2
...,...,...,...,...
5779,Symptoms of Anxiety Disorder or Depressive Dis...,Virginia,3/17/2021 0:00,31.4
5780,Symptoms of Anxiety Disorder or Depressive Dis...,Washington,3/17/2021 0:00,35.6
5781,Symptoms of Anxiety Disorder or Depressive Dis...,West Virginia,3/17/2021 0:00,41.0
5782,Symptoms of Anxiety Disorder or Depressive Dis...,Wisconsin,3/17/2021 0:00,32.3
5783,Symptoms of Anxiety Disorder or Depressive Dis...,Wyoming,3/17/2021 0:00,35.6

In [3]:
# Collect a list of all the unique values in "date"
anx_data["Time Period Start Date"].unique()

array(['4/23/2020 0:00', '5/7/2020 0:00', '5/14/2020 0:00',
       '5/21/2020 0:00', '5/28/2020 0:00', '6/4/2020 0:00',
       '6/11/2020 0:00', '6/18/2020 0:00', '6/25/2020 0:00',
       '7/2/2020 0:00', '7/9/2020 0:00', '7/16/2020 0:00',
       '7/22/2020 0:00', '8/19/2020 0:00', '9/2/2020 0:00',
       '9/16/2020 0:00', '9/30/2020 0:00', '10/14/2020 0:00',
       '10/28/2020 0:00', '11/11/2020 0:00', '11/25/2020 0:00',
       '12/9/2020 0:00', '12/22/2020 0:00', '1/6/2021 0:00',
       '1/20/2021 0:00', '2/3/2021 0:00', '2/17/2021 0:00',
       '3/3/2021 0:00', '3/17/2021 0:00'], dtype=object)

In [4]:
# Looking only at 04/23/2020
anx_042320_df = anx_data.loc[anx_data["Time Period Start Date"] == "4/23/2020 0:00", :]
anx_042320_df

,Indicator,State,Time Period Start Date,Value
0,Symptoms of Depressive Disorder,United States,4/23/2020 0:00,23.5
1,Symptoms of Depressive Disorder,United States,4/23/2020 0:00,32.7
2,Symptoms of Depressive Disorder,United States,4/23/2020 0:00,25.7
3,Symptoms of Depressive Disorder,United States,4/23/2020 0:00,24.8
4,Symptoms of Depressive Disorder,United States,4/23/2020 0:00,23.2
...,...,...,...,...
205,Symptoms of Anxiety Disorder or Depressive Dis...,Virginia,4/23/2020 0:00,33.7
206,Symptoms of Anxiety Disorder or Depressive Dis...,Washington,4/23/2020 0:00,35.0
207,Symptoms of Anxiety Disorder or Depressive Dis...,West Virginia,4/23/2020 0:00,34.3
208,Symptoms of Anxiety Disorder or Depressive Dis...,Wisconsin,4/23/2020 0:00,31.1
209,Symptoms of Anxiety Disorder or Depressive Dis...,Wyoming,4/23/2020 0:00,31.0

In [5]:
#Calculate average anxiety level as of 04/23/20
avg_anx_042320 = (anx_042320_df["Value"]).mean()
avg_anx_042320_df = pd.DataFrame({"Average American anxiety level as of 04/23/20": [avg_anx_042320]})
avg_anx_042320_df

   Average American anxiety level as of 04/23/20
0                                      29.150952

In [6]:
anx_093020_df = anx_data.loc[anx_data["Time Period Start Date"] == "9/30/2020 0:00", :]
anx_093020_df.head()

,Indicator,State,Time Period Start Date,Value
3207,Symptoms of Depressive Disorder,United States,9/30/2020 0:00,25.4
3208,Symptoms of Depressive Disorder,United States,9/30/2020 0:00,39.3
3209,Symptoms of Depressive Disorder,United States,9/30/2020 0:00,28.4
3210,Symptoms of Depressive Disorder,United States,9/30/2020 0:00,26.4
3211,Symptoms of Depressive Disorder,United States,9/30/2020 0:00,22.6

In [7]:
avg_anx_093020 = (anx_093020_df["Value"]).mean()
avg_anx_093020_df = pd.DataFrame({"Average American anxiety level as of 09/30/20": [avg_anx_093020]})
avg_anx_093020_df

   Average American anxiety level as of 09/30/20
0                                      30.998095

In [8]:
anx_031721_df = anx_data.loc[anx_data["Time Period Start Date"] == "3/17/2021 0:00", :]
anx_031721_df.head()

,Indicator,State,Time Period Start Date,Value
5574,Symptoms of Depressive Disorder,United States,3/17/2021 0:00,24.6
5575,Symptoms of Depressive Disorder,United States,3/17/2021 0:00,38.2
5576,Symptoms of Depressive Disorder,United States,3/17/2021 0:00,28.2
5577,Symptoms of Depressive Disorder,United States,3/17/2021 0:00,25.0
5578,Symptoms of Depressive Disorder,United States,3/17/2021 0:00,22.5

In [9]:
avg_anx_031721 = (anx_031721_df["Value"]).mean()
avg_anx_031721_df = pd.DataFrame({"Average American anxiety level as of 03/17/21": [avg_anx_031721]})
avg_anx_031721_df

   Average American anxiety level as of 03/17/21
0                                      29.451905